### ISSUE TITLE
Regarding the calculation of multi-scale graphics when disentangling is set to False.

### ISSUE THREAD

**Issue by a14en9** [kenziyuliu/MS-G3D#23]
Hi,

Really great work!

Can you explain the code 31-34 in the "ms_gcn.py" file? Is this the correct way to calculate multi-scale graphs without disentangling? Because the "k" on line 31 has not been used.

Thanks in advance.

**Comment by kenziyuliu** [comment]
Hi there,

Thanks for your interest. The `else` branch you are referring to is computing the adjacency powers:
- L31: initialize `k` adjacency matrices in the form `A_hat = A + I`
- L32: normalize them (first paragraph of Section 3.2)
- L33: take powers for 0 to k-1, so `A_powers` are `[A_hat^0 = I, A_hat^1 = A_hat, A_hat^2, A_hat^3, ...]`
- L34: batch them for multi-scale aggregation

i.e. L31 only makes `k` copies, and L33 is raising the powers. 

Hope this helps :).

**Comment by a14en9** [comment]
Hi,

Thank you for your prompt reply.

Because I just came across this direction, so change the four lines of code you wrote to the following form, can you please help me see if it is correct?
A_powers = [np.linalg.matrix_power(A_binary+np.eye(len(A_binary)), k) for k in range(num_scales)]
A_powers = np.concatenate([normalize_adjacency_matrix(g) for g in A_powers])

Very grateful for your help!

**Comment by kenziyuliu** [comment]
Your code changes to "take power first, then normalize", which can potentially lead to instabilities due to the large matrix entries with large `k`. You can certainly do this, though I'm not quite sure about the motivation.  I would also add that if `k` is small, either way should be fine (NN weights can probably adapt to the minor differences).

EDIT: see also https://arxiv.org/pdf/1905.00067.pdf as an example where power is raised after normalization

**Comment by a14en9** [comment]
Really appreciate your help and I will look into it carefully.
