### ISSUE TITLE
"kinetics_gendata.py" Error

### ISSUE THREAD

**Issue by yaki-toki** [kenziyuliu/MS-G3D#32]
When I executed this file as it is, the following error was printed.
"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"
I don't know if it's a problem with the file uploaded to Google drive or the A-z order.

So I changed the order of the list of 'part' variables in line 173 of the file.
`part = ['val', 'train']` modified this code as `part = ['train', 'val']`.

solved it

**Comment by kenziyuliu** [comment]
Hi there, thanks a lot for your interest! Well done on solving your issue too. This is very interesting because if we look at L173-181, we are just building the filename strings for reading the dataset files, and I would assume the order for reading the files shouldn't matter (though it's been quite a while since I last loaded the dataset). I would suggesting re-downloading the data, re-cloning a copy of this repo, and re-running this file to see if this is indeed the issue.
