### ISSUE TITLE
 I can't reproducing the results of the paper

### ISSUE THREAD

**Issue by wjm-wjm** [kenziyuliu/MS-G3D#7]
Hi, here
 I use your pretrained model of kinetics, but I can't reproducing the results of the paper. Is something I did wrong? (I think that I generate data in a correct way according to the README.md, while I have changed some file paths of your code for convenience, just like the path of dataset )
  
![2020-06-21 16-53-33屏幕截图](https://user-images.githubusercontent.com/53390698/85220829-61520480-b3e1-11ea-8a22-02ad39a3677a.png)
![2020-06-21 17-02-57屏幕截图](https://user-images.githubusercontent.com/53390698/85220816-4a131700-b3e1-11ea-8c62-2a6352fd8d75.png)
![2020-06-21 16-46-53屏幕截图](https://user-images.githubusercontent.com/53390698/85220847-79c21f00-b3e1-11ea-9f50-b6030d0912d9.png)
![2020-06-21 16-48-42屏幕截图](https://user-images.githubusercontent.com/53390698/85220850-80e92d00-b3e1-11ea-9cf4-59e8d7a5172f.png)

**Comment by kenziyuliu** [comment]
Hi there, 

It appears that you didn't set up the bone stream data for Kinetics correctly. I would suggest:

- Carefully checking whether your data are set up properly according to README
- Checking the paths to your data
- Follow `eval_pretrained.sh` for the testing commands

I just ran a sanity check and the pre-trained joint model gives 35.8% (which you also obtained), the pre-trained bone model gives 35.4%, and the ensemble gives 38.0%. Since you have 2.6% for bone stream evaluation, you might be testing on the wrong data. Feel free to re-open the issue if the problem persists.

**Comment by wjm-wjm** [comment]
Oh, I did something wrong when I generated bone data. The result now is right. You did a really nice work! Thanks ~



发自我的iPhone


------------------ Original ------------------
